apiVersion: v1
kind: Service
metadata:
  name: redayit-frontend-service
  namespace: redayit-frontend
spec:
  type: ClusterIP
  selector:
    app: redayit-frontend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001