apiVersion: apps/v1
kind: Deployment
metadata:
  name: redayit-frontend
  namespace: redayit-frontend
  labels:
    app: redayit-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redayit-frontend
  template:
    metadata:
      labels:
        app: redayit-frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        # ... rest of your deployment config